name: Playwright Tests
on:
  deployment_status:
jobs:
  test:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    if: github.event.deployment_status.state == 'success'
    container: 
      image: mcr.microsoft.com/playwright:v1.50.1-noble
      options: --user 1001
    steps:
    - uses: actions/checkout@v4
    - name: Setup pnpm
      uses: pnpm/action-setup@v4.1.0
      with: 
        version: 10.4.1
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
        cache: 'pnpm'
    - name: Install dependencies
      run: pnpm install
    - name: Build app
      run: pnpm run build
    - name: Install Playwright Browsers
      run: pnpm exec playwright install --with-deps
    - name: Run Playwright tests
      run: pnpm run test
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 15
